### ISSUE TITLE
Issues with license

### ISSUE THREAD

**Issue by alexzielenski** [MacEnhance/PaintCan#1]
> Pretty much the BSD license, just don't repackage it and call it your own please!

Nice extension you have here. I found particular irony in this line of your README since I have had multiple issues with you plagiarizing my past work (dockify, binventory, FlashLight update). 

https://github.com/ParasiteTeam/extensions/tree/master/FreshPaint

You adjusted just enough of the code to make the method seem novel. But the inclusion of my ZKSwizzle, combined with the name PaintCan, combined with the below points makes me believe with strong conviction this may be another instance of my past years' projects which you have repackaged and called your own. 

Verbatim README:

> PaintCan is a MacForge Plugin that allows hotswapping car files on the fly without replacing any System files.

> FreshPaint Allows hotswapping car files on the fly without replacing any System files.

You even still have our old ParasiteTeam copyright:

https://github.com/MacEnhance/PaintCan/blob/master/PaintCan/Info.plist#L24

Also see:

https://github.com/MacEnhance/PaintCan/blob/master/PaintCan.xcodeproj/project.pbxproj#L81

@w0lfschild You ask others to do you this courtesy so why do lack the decency to do so yourself? Why did you make the active decision to not fork and to instead rename the project without including the original license?

**Comment by w0lfschild** [comment]
> @w0lfschild You ask others to do you this courtesy so why do lack the decency to do so yourself? Why did you make the active decision to not fork and to instead rename the project without including the original license?

I do just use that as a copy paste in every plugin README.

> Nice extension you have here. I found particular irony in this line of your README since I have had multiple issues with you plagiarizing my past work (dockify, binventory, FlashLight update). You adjusted just enough of the code to make the method seem novel. But the inclusion of my ZKSwizzle, combined with the name PaintCan, combined with the below points makes me believe with strong conviction this may be another instance of my past years' projects which you have repackaged and called your own. 

Not sure what I did regarding flashlight (it's forked off your branch and has a link to your fork in the readme) or dockify (I assume cDock related but it is credited as well as licenses are included for zkswizzle and binventory) but I do recall not [attributing binvintory](https://github.com/w0lfschild/binventory_SIMBL/issues/2) in a similar issue where I modified your source code to get a version working version using something other than the parasite loader.

In this case I had originally just wanted to modify FreshPaint to run using MacForge but I wasn't able to get any result from what I could tell. In the end I re-wrote `FreshPaint.m` in what I personally feel like is different implementation.

I definitely don't mean you any slight. You do great work in the iOS/macOS hacker space. I use ZKSwizzle in pretty much any project that involves method swizzling because I like the simple, straight forward implementation.

You're right I should include attribution to FreshPaint as a starting point for this. Just like in the case of binventory I'm fine with including attribution however you'd like. I think I'm realizing that ZKSwizzle should have a license included in the repo as well but if there's anything else I'm missing feel free to let me know here or in an e-mail.

**Comment by w0lfschild** [comment]
@alexzielenski 

At this point I've included information that indicates this project is based on FreshPaint as well as using ZKSwizzle and included the licenses for each in the project. As I have spare time I'll update my other projects that use ZKSwizzle to include the license and a link to the repo.
